### ISSUE TITLE
"What Application to Build?" does not clearly convey that this section is about generating ideas for third-party devs.

### ISSUE THREAD

**Issue by tashachin** [prifina/prifina-app-starter#22]
- [ ] Rename the header.
- [ ] Reorder the existing copy to be more organized in delivery.
- [ ] Revise the copy to be more accurate and concise.

**Comment by tashachin** [comment]
> If you are wondering what data is available to build your application on, you can download the type of data that the users have, from looking at the [Prifina Your Data](https://www.prifina.com/your-data.html) page.

@mmlampinen - Is the implication here that the developer can see what data fields are available in a report that they download at that link?

I think it makes more sense for the potential data types to be exposed on the developer portal instead of having a 3rd-party dev switch to their end-user account and run through the user story to see what data they get back.

**Comment by mmlampinen** [comment]
@tashachin Correct, the developer account will have that information. That being said, that requires registration. So that page is public and allows a dev to explore data sources themselves, by looking at their own data, without any registration with Prifina. There will also be a public data model page on docs.prifina.com for the data model, but it is not going to contain any real data, only how it is organized.

**Comment by tashachin** [comment]
![image](https://user-images.githubusercontent.com/27714199/111625159-c8062200-87a9-11eb-8f6a-11b2a7284146.png)

![image](https://user-images.githubusercontent.com/27714199/111625179-cccad600-87a9-11eb-8d51-b5d4023f3503.jpeg)

**Comment by mmlampinen** [comment]
What was this last comment referring to? @tashachin

**Comment by tashachin** [comment]
I must have been up late again, confusing grammar for another concern.
