### ISSUE TITLE
[ documentation, invalid ] TLDR section is not user-friendly and needs a renaming.

### ISSUE THREAD

**Issue by tashachin** [prifina/prifina-app-starter#9]
It's very unclear what this section's purpose is and why "[What Application to Build?](https://github.com/tashachin/prifina-app-starter#what-application-to-build)" and "[How to Start?](https://github.com/tashachin/prifina-app-starter#how-to-start)" are nested beneath it.

**Comment by mmlampinen** [comment]
Maybe this could be the introduction to the starter app repo and overall Prifina platform. Feel free to re-write

**Comment by tashachin** [comment]
I'm reading over the copy underneath **TLDR** and I agree, it's well-suited as an Introduction.

@mmlampinen - Could you clarify this sentence for me?
> Wait to register as a developer to get an appID or contact one of our team on Slack to get ahead of the line.

"Get ahead of the line"? Is there a queue (for beta access or something?)

**Comment by mmlampinen** [comment]
Hey @tashachin - in a manner of speaking. I'm not exactly sure of the tone of the sentence, but in practice right now we are not accepting "outside apps", where "outside" means from developers not already on our Prifina dev slack or the LED slack. This is just because we can't handle outside apps right now, but in practice it also means we will prioritize those developers who we already know as we start opening up the platform.
